/*
  Warnings:

  - You are about to drop the `school_info` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropTable
DROP TABLE `school_info`;

-- CreateTable
CREATE TABLE `SchoolInfo` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `description` TEXT NULL,
    `motto` TEXT NULL,
    `vision` TEXT NULL,
    `mission` TEXT NULL,
    `studentCount` INTEGER NOT NULL DEFAULT 0,
    `staffCount` INTEGER NOT NULL DEFAULT 0,
    `openDate` DATETIME(3) NOT NULL,
    `closeDate` DATETIME(3) NOT NULL,
    `subjects` JSON NOT NULL,
    `departments` JSON NOT NULL,
    `videoTour` TEXT NULL,
    `videoType` VARCHAR(20) NULL,
    `videoThumbnail` TEXT NULL,
    `feesDay` DOUBLE NULL,
    `feesBoarding` DOUBLE NULL,
    `admissionFee` DOUBLE NULL,
    `feesDayDistributionJson` JSON NULL,
    `feesBoardingDistributionJson` JSON NULL,
    `admissionFeeDistribution` JSON NULL,
    `admissionOpenDate` DATETIME(3) NULL,
    `admissionCloseDate` DATETIME(3) NULL,
    `admissionRequirements` TEXT NULL,
    `admissionCapacity` INTEGER NULL,
    `admissionContactEmail` VARCHAR(255) NULL,
    `admissionContactPhone` VARCHAR(50) NULL,
    `admissionWebsite` VARCHAR(255) NULL,
    `admissionLocation` TEXT NULL,
    `admissionOfficeHours` VARCHAR(100) NULL,
    `admissionDocumentsRequired` JSON NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `lastFileUpdate` DATETIME(3) NULL,
    `curriculumPDF` TEXT NULL,
    `curriculumPdfName` VARCHAR(255) NULL,
    `curriculumPdfSize` INTEGER NULL,
    `curriculumPdfUploadDate` DATETIME(3) NULL,
    `curriculumPdfMetadata` JSON NULL,
    `feesDayDistributionPdf` TEXT NULL,
    `feesDayPdfName` VARCHAR(255) NULL,
    `feesDayPdfSize` INTEGER NULL,
    `feesDayPdfUploadDate` DATETIME(3) NULL,
    `feesDayPdfMetadata` JSON NULL,
    `feesBoardingDistributionPdf` TEXT NULL,
    `feesBoardingPdfName` VARCHAR(255) NULL,
    `feesBoardingPdfSize` INTEGER NULL,
    `feesBoardingPdfUploadDate` DATETIME(3) NULL,
    `feesBoardingPdfMetadata` JSON NULL,
    `admissionFeePdf` TEXT NULL,
    `admissionFeePdfName` VARCHAR(255) NULL,
    `admissionFeePdfSize` INTEGER NULL,
    `admissionFeePdfUploadDate` DATETIME(3) NULL,
    `admissionFeePdfMetadata` JSON NULL,
    `videoMetadata` JSON NULL,
    `thumbnailMetadata` JSON NULL,
    `form1ResultsPdf` TEXT NULL,
    `form1ResultsPdfName` VARCHAR(255) NULL,
    `form1ResultsPdfSize` INTEGER NULL,
    `form1ResultsYear` INTEGER NULL,
    `form1ResultsUploadDate` DATETIME(3) NULL,
    `form1ResultsMetadata` JSON NULL,
    `form2ResultsPdf` TEXT NULL,
    `form2ResultsPdfName` VARCHAR(255) NULL,
    `form2ResultsPdfSize` INTEGER NULL,
    `form2ResultsYear` INTEGER NULL,
    `form2ResultsUploadDate` DATETIME(3) NULL,
    `form2ResultsMetadata` JSON NULL,
    `form3ResultsPdf` TEXT NULL,
    `form3ResultsPdfName` VARCHAR(255) NULL,
    `form3ResultsPdfSize` INTEGER NULL,
    `form3ResultsYear` INTEGER NULL,
    `form3ResultsUploadDate` DATETIME(3) NULL,
    `form3ResultsMetadata` JSON NULL,
    `form4ResultsPdf` TEXT NULL,
    `form4ResultsPdfName` VARCHAR(255) NULL,
    `form4ResultsPdfSize` INTEGER NULL,
    `form4ResultsYear` INTEGER NULL,
    `form4ResultsUploadDate` DATETIME(3) NULL,
    `form4ResultsMetadata` JSON NULL,
    `mockExamsResultsPdf` TEXT NULL,
    `mockExamsPdfName` VARCHAR(255) NULL,
    `mockExamsPdfSize` INTEGER NULL,
    `mockExamsYear` INTEGER NULL,
    `mockExamsUploadDate` DATETIME(3) NULL,
    `mockExamsMetadata` JSON NULL,
    `kcseResultsPdf` TEXT NULL,
    `kcsePdfName` VARCHAR(255) NULL,
    `kcsePdfSize` INTEGER NULL,
    `kcseYear` INTEGER NULL,
    `kcseUploadDate` DATETIME(3) NULL,
    `kcseMetadata` JSON NULL,
    `additionalResultsFiles` JSON NULL,
    `additionalFilesMetadata` JSON NULL,
    `additionalFilesUploadDate` DATETIME(3) NULL,
    `totalFileCount` INTEGER NOT NULL DEFAULT 0,
    `totalFileSizeBytes` BIGINT NOT NULL DEFAULT 0,
    `totalFileSizeMB` DOUBLE NULL DEFAULT 0,
    `fileStorageSummary` JSON NULL,
    `fileOperationsHistory` JSON NULL,
    `fileVersions` JSON NULL,
    `fileAccessLog` JSON NULL,
    `fileMappings` JSON NULL,
    `fileCategories` JSON NULL,
    `storageConfig` JSON NULL,
    `lastFileUpdateBy` VARCHAR(255) NULL,
    `fileIntegrityChecks` JSON NULL,
    `retentionPolicy` JSON NULL,
    `systemMetadata` JSON NULL,

    INDEX `SchoolInfo_name_idx`(`name`),
    INDEX `SchoolInfo_admissionOpenDate_admissionCloseDate_idx`(`admissionOpenDate`, `admissionCloseDate`),
    INDEX `SchoolInfo_kcseYear_idx`(`kcseYear`),
    INDEX `SchoolInfo_totalFileCount_idx`(`totalFileCount`),
    INDEX `SchoolInfo_lastFileUpdate_idx`(`lastFileUpdate`),
    INDEX `SchoolInfo_createdAt_idx`(`createdAt`),
    INDEX `SchoolInfo_updatedAt_idx`(`updatedAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
